#= require angular/angular
#= require angular-animate/angular-animate
#= require angular-sanitize/angular-sanitize
#= require angular-ui-router/release/angular-ui-router
#= require ionic/release/js/ionic
#= require ionic/release/js/ionic-angular
#= require app
#= require_tree ./controllers/.
# require_tree ./factories/.
# require_tree ./services/.
